trigger:
- main

pool:
  name: ziv's machine
  demands:
    - java
    - Agent.Version -gtVersion 3.218.0

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'  

# - script: |
#     dotnet build --configuration Release
#   displayName: 'Build Solution'

# - script: |
#     dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
#   displayName: 'Publish Artifacts'

# - script: |
#     dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory)/nupkg
#   displayName: 'Pack Solution'

- script: |
    # Increment version number dynamically
    dotnet build /p:Version=$(Build.BuildId) --configuration Release
    dotnet pack /p:PackageVersion=$(Build.BuildId) --configuration Release --output $(Build.ArtifactStagingDirectory)/nupkg
  displayName: 'Build and Pack Solution'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: NuGetAuthenticate@0

- script: |
    echo "Starting NuGet push..."
    dotnet nuget push --source "https://pkgs.dev.azure.com/zivgl66/e01e2b10-f19f-4ceb-b944-8d8db1edeee7/_packaging/helloworldfeed/nuget/v3/index.json" --api-key $(NUGET_API_KEY) "$(Build.ArtifactStagingDirectory)/nupkg/*.nupkg" 
  displayName: 'Publish to Azure Artifacts'
  env:
    NUGET_API_KEY: $(NUGET_API_KEY) 