trigger:
- main

pool:
  name: "ziv's machine"
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'  # This ensures the latest .NET SDK within the 7.0 series is used

- script: |
    dotnet build --configuration Release
  displayName: 'Build Solution'

- script: |
    dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: NuGetAuthenticate@0

- script: |
    echo "Starting NuGet push..."
    dotnet nuget push --source "helloworldfeed" --api-key $(NUGET_API_KEY) "$(Build.ArtifactStagingDirectory)/*.nupkg" 
  displayName: 'Publish to Azure Artifacts'
  env:
    NUGET_API_KEY: $(NUGET_API_KEY) 