trigger:
- main

pool:
  name: "ziv's machine"
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'  

- script: |
    dotnet build --configuration Release
  displayName: 'Build Solution'

- script: |
    dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Artifacts'

- script: |
    dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory)/nupkg
  displayName: 'Pack Solution'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: NuGetAuthenticate@0

- script: |
    echo "Starting NuGet push..."
    dotnet nuget push --source "https://pkgs.dev.azure.com/zivgl66/zivgl66@gmail.com/_packaging/helloworldfeed/nuget/v3/index.json" --api-key "hello" "$(Build.ArtifactStagingDirectory)/nupkg/*.nupkg" 
  displayName: 'Publish to Azure Artifacts'
  env:
    NUGET_API_KEY: $(NUGET_API_KEY) 