trigger:
- main

pool:
  name: "ziv's machine"
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.x'  # This ensures the latest .NET SDK within the 7.0 series is used

- script: |
    dotnet build --configuration Release
  displayName: 'Build Solution'

- script: |
    dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: NuGetAuthenticate@0

- script: |
    dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg -k $(NUGET_API_KEY) -s https://pkgs.dev.azure.com/zivgl66/hello%20world/_packaging/helloworldfeed/nuget/v3/index.json
  displayName: 'Publish to Azure Artifacts'